services:
  wordpress:
    image: wordpress
    ports:
    - "8089:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "coffee"
      WORDPRESS_DB_NAME: wordpress

  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "coffee"
    volumes:
      - ./App/wordpress/mysql:/var/lib/mysql

  dind:
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - docker-data:/var/lib/docker
    ports:
      - "2375:2375"
  
  doom-app:
    image: callumhoughton22/doom-in-docker:0.1
    restart: always
    ports: 
        - 8080:8080

  vue-app:
    build: 
      context: app/vue/docker-demo-vue
      dockerfile: dockerfile
    restart: unless-stopped
    ports:
      - "8001:5173"
  
  react-app:
    build: 
      context: app/react/docker-demo-react
      dockerfile: dockerfile
    restart: unless-stopped
    ports:
      - "8002:5172"

  angular-app:
    build: 
      context: app/angular/docker-demo-angular
      dockerfile: dockerfile
    restart: unless-stopped
    ports:
      - "8003:5171"

volumes:
  docker-certs-ca:
  docker-certs-client:
  docker-data: