services:
  wordpress:
    image: wordpress
    ports:
    - "8089:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "coffee"
      WORDPRESS_DB_NAME: wordpress
    restart: unless-stopped

  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "coffee"
    volumes:
      - ./App/wordpress/mysql:/var/lib/mysql
    restart: unless-stopped

  dind:
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - docker-data:/var/lib/docker
    ports:
      - "2375:2375"
    restart: unless-stopped

  doom-app:
    image: callumhoughton22/doom-in-docker:0.1
    ports: 
        - 8080:8080
    restart: unless-stopped

  vue-app:
    build: 
      context: app/vue/docker-demo-vue
      dockerfile: dockerfile
    ports:
      - "8001:5173"
    restart: unless-stopped
  
  react-app:
    build: 
      context: app/react/docker-demo-react
      dockerfile: dockerfile
    ports:
      - "8002:5172"
    restart: unless-stopped

  angular-app:
    build: 
      context: app/angular/docker-demo-angular
      dockerfile: dockerfile
    ports:
      - "8003:4200"
    restart: unless-stopped
  
  sql:
    user: root
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SuperSecret1!
    ports:
      - 11433:1433
    volumes:
      - dbdata:/var/opt/mssql/data
      - dblog:/var/opt/mssql/log
      - dbsecrets:/var/opt/mssql/secrets
    restart: unless-stopped

volumes:
  docker-certs-ca:
  docker-certs-client:
  docker-data:
  dbdata:
  dblog:
  dbsecrets: